#!/usr/bin/env bash
# Build the icarus-dev Docker image.
#
#   scripts/docker-build.sh              build (cached layers are reused)
#   scripts/docker-build.sh --no-cache   full rebuild; other args go to `docker compose build`
#
# Rebuild after bumping the innate-os submodule or editing docker/Dockerfile. Source
# edits never need a rebuild -- the repo is bind-mounted.
set -euo pipefail

ICARUS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INNATE="$ICARUS_ROOT/innate-os"
COMPOSE=(docker compose -f "$ICARUS_ROOT/docker/docker-compose.yml")

warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$*" >&2; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

# sha256sum isn't on a stock macOS toolchain, but this script is advertised for macOS
# via setup.sh; shasum -a 256 is the portable equivalent.
sha256() {
    if have sha256sum; then
        sha256sum
    else
        shasum -a 256
    fi
}

[ ! -f /.dockerenv ] || die "Run this on the host, not inside the container."
have docker || die "Docker is not installed. Run scripts/setup.sh first."
docker info >/dev/null 2>&1 ||
    die "Cannot reach the Docker daemon. Start Docker, or if you were just added to the 'docker' group, log out and back in."
[ -f "$INNATE/sim/launcher/config.py" ] ||
    die "innate-os submodule is missing. Run: git submodule update --init --recursive"

# The published deps image is content-addressed by the innate-os files that build it,
# so asking innate-os's launcher for the hash keeps icarus on exactly the right base.
deps_hash() {
    if have python3 && python3 -c 'import sys; sys.exit(sys.version_info < (3, 10))'; then
        python3 "$INNATE/sim/launcher/config.py" deps-image-hash
        return
    fi
    local uv
    uv="$(command -v uv || echo "$HOME/.local/bin/uv")"
    [ -x "$uv" ] || die "Need Python >= 3.10 or uv to compute the innate-os image hash."
    "$uv" run --no-project --python 3.11 --quiet python "$INNATE/sim/launcher/config.py" deps-image-hash
}

hash="$(deps_hash)"
published="ghcr.io/innate-inc/innate-os-sim-deps:deps-$hash"
local_tag="innate-os-sim-clean-innate:inputs-$hash"

if docker image inspect "$local_tag" >/dev/null 2>&1; then
    base_image="$local_tag"
elif docker image inspect "$published" >/dev/null 2>&1 || docker pull "$published"; then
    base_image="$published"
else
    warn "No published innate-os deps image for this submodule commit; building it locally (25-30 min, once)."
    docker build --network host -f "$INNATE/sim/Dockerfile" --target dev-runtime -t "$local_tag" "$INNATE"
    base_image="$local_tag"
fi

# Mirrors HOST_REPO_ID in innate-os/sim/launcher/config.py: sha256 of the checkout's resolved path.
repo_id="$(printf '%s' "$(cd "$INNATE" && pwd -P)" | sha256 | cut -c1-16)"
cat >"$ICARUS_ROOT/docker/.env" <<EOF
# Generated by scripts/docker-build.sh -- machine-specific, do not commit.
INNATE_BASE_IMAGE=$base_image
INNATE_SIM_CONTAINER=innate-dev-$repo_id
EOF

echo "==> Building icarus-dev:latest on $base_image"
"${COMPOSE[@]}" build "$@"
echo
echo "Done. Enter the container with: scripts/docker-shell.sh"
